// Renders a single report (complaint, wildlife turnover, or service request)
// into a printable PDF for CENRO staff hardcopy files. Pure layout over the
// detail object the staff services already return - no DB access here.
//
// These documents are produced behind staff/admin RBAC and intentionally
// include reporter contact details, which staff need to act on a case. The
// zero-personal-data rule (R.A. 10173) governs PUBLIC endpoints, not this one,
// so the footer reminds whoever holds the printout of that duty.

const { GREEN, MUTED, humanize, heading, drawRow, kv, paragraph, createReportDocument } = require('./report.layout');

const fmt = (d) => (d ? new Date(d).toLocaleString('en-PH') : 'Not set');
const yesNo = (v) => (v ? 'Yes' : 'No');

const KINDS = {
  complaint: { label: 'Complaint Report', idField: 'tracking_id' },
  wildlife: { label: 'Wildlife Turnover Report', idField: 'reference_id' },
  request: { label: 'Service Request Report', idField: 'tracking_id' },
};

function titleBlock(doc, kind, ref, meta) {
  const left = doc.page.margins.left;
  doc.fontSize(22).font('Helvetica-Bold').fillColor(GREEN).text('CENROWATCH', left, doc.y);
  doc.fontSize(11).font('Helvetica').fillColor(MUTED).text('CENRO Cabuyao - Environmental Monitoring System');
  doc.fontSize(13).font('Helvetica-Bold').fillColor('#000').text(KINDS[kind].label);
  doc.fontSize(10).font('Helvetica-Bold').fillColor(GREEN).text(ref);
  doc.fontSize(9).font('Helvetica').fillColor(MUTED)
    .text(`Generated ${fmt(meta.generatedAt || Date.now())}${meta.by ? ` by ${meta.by}` : ''}`);
  doc.fillColor('#000');
}

// Who filed it. Walk-in and anonymous reports have no linked account, so the
// printout must say so explicitly rather than leaving the field blank.
function reporterBlock(doc, r) {
  heading(doc, 'Reporter');
  if (r.is_anonymous) {
    kv(doc, [['Reporter', 'Anonymous (no identity collected)']]);
    if (r.logged_by_staff) {
      kv(doc, [['Logged by', `${r.logged_by_staff.first_name} ${r.logged_by_staff.last_name}`]]);
    }
    return;
  }
  if (r.logged_by) {
    kv(doc, [
      ['Reporter', r.reporter_name || 'Not recorded'],
      ['Contact', r.reporter_contact || 'Not recorded'],
      ['Received via', humanize(r.received_via || 'Walk_In')],
      ['Logged by', r.logged_by_staff ? `${r.logged_by_staff.first_name} ${r.logged_by_staff.last_name}` : 'Not recorded'],
    ]);
    return;
  }
  const u = r.user || r.resident;
  kv(doc, [
    ['Reporter', u ? `${u.first_name} ${u.last_name}` : 'Not recorded'],
    ['Email', u?.email || 'Not recorded'],
    ['Contact', u?.contact_number || 'Not recorded'],
  ]);
}

function locationBlock(doc, r) {
  const hasGeo = r.latitude != null && r.longitude != null;
  if (!hasGeo && !r.address_details) return;
  heading(doc, 'Location');
  if (r.address_details) paragraph(doc, r.address_details);
  if (hasGeo) kv(doc, [['Coordinates', `${r.latitude}, ${r.longitude}`]]);
}

function notesBlock(doc, r) {
  if (!r.staff_notes && !r.resolution_notes) return;
  heading(doc, 'CENRO Notes');
  if (r.staff_notes) paragraph(doc, r.staff_notes);
  if (r.resolution_notes) {
    doc.moveDown(0.4);
    paragraph(doc, 'Resolution', { bold: true, size: 9 });
    paragraph(doc, r.resolution_notes);
  }
}

function historyBlock(doc, r) {
  const rows = r.status_history || [];
  heading(doc, 'Status History');
  if (rows.length === 0) {
    paragraph(doc, 'No status changes recorded.', { color: MUTED, size: 9 });
    return;
  }
  const left = doc.page.margins.left;
  drawRow(doc, [
    { text: 'Date', x: left, w: 130 },
    { text: 'Change', x: left + 130, w: 160 },
    { text: 'Note', x: left + 290, w: 205 },
  ], { bold: true, color: MUTED });
  for (const h of rows) {
    drawRow(doc, [
      { text: fmt(h.changed_at), x: left, w: 130 },
      { text: `${humanize(h.old_status)} to ${humanize(h.new_status)}`, x: left + 130, w: 160 },
      { text: h.note || '-', x: left + 290, w: 205 },
    ]);
  }
}

function footer(doc) {
  doc.moveDown(1.5);
  doc.fontSize(8).font('Helvetica').fillColor(MUTED)
    .text('Generated by CENROWATCH. Contains personal data. Handle per R.A. 10173.', { align: 'center' });
  doc.fillColor('#000');
}

function writeComplaintReport(doc, c, meta = {}) {
  titleBlock(doc, 'complaint', c.tracking_id, meta);
  heading(doc, 'Summary');
  kv(doc, [
    ['Type', humanize(c.complaint_type)],
    ['Status', humanize(c.status)],
    ['Priority', yesNo(c.priority)],
    ['Barangay', c.barangay?.name || 'Not set'],
    ['Filed', fmt(c.submitted_at)],
    ['Date observed', fmt(c.observed_at)],
    ['SLA deadline', fmt(c.sla_deadline)],
    ['SLA breached', yesNo(c.exceeded_sla)],
    ['Resolved', fmt(c.resolved_at)],
    ['Assigned to', c.assigned_staff ? `${c.assigned_staff.first_name} ${c.assigned_staff.last_name}` : 'Unassigned'],
    ['Photo attached', yesNo(c.photo_path)],
  ]);
  heading(doc, 'Description');
  paragraph(doc, c.description || 'No description provided.');
  locationBlock(doc, c);
  reporterBlock(doc, c);
  notesBlock(doc, c);
  historyBlock(doc, c);
  footer(doc);
}

function writeWildlifeReport(doc, w, meta = {}) {
  titleBlock(doc, 'wildlife', w.reference_id, meta);
  heading(doc, 'Summary');
  kv(doc, [
    ['Species', w.species_name || 'Not recorded'],
    ['Category', w.species_category || 'Not set'],
    ['Endangered', w.is_endangered ? 'Yes (priority review)' : 'No'],
    ['Condition', humanize(w.animal_condition)],
    ['Status', humanize(w.status)],
    ['Barangay', w.barangay?.name || 'Not set'],
    ['Filed', fmt(w.submitted_at)],
    ['SLA deadline', fmt(w.sla_deadline)],
    ['SLA breached', yesNo(w.exceeded_sla)],
    ['Intake', fmt(w.intake_date)],
    ['Released', fmt(w.release_date)],
    ['Transfer destination', w.transfer_destination || 'Not set'],
    ['Custody photos', String((w.chain_of_custody_photos || []).length)],
    ['Photo attached', yesNo(w.photo_path)],
  ]);
  heading(doc, 'Description');
  paragraph(doc, w.description || 'No description provided.');
  locationBlock(doc, w);
  reporterBlock(doc, w);
  notesBlock(doc, w);
  historyBlock(doc, w);
  footer(doc);
}

function writeRequestReport(doc, r, meta = {}) {
  titleBlock(doc, 'request', r.tracking_id, meta);
  heading(doc, 'Summary');
  kv(doc, [
    ['Service', humanize(r.request_type)],
    ['Status', humanize(r.status)],
    ['Barangay', r.barangay?.name || 'Not set'],
    ['Quantity requested', r.requested_quantity == null ? 'Not set' : String(r.requested_quantity)],
    ['Preferred schedule', fmt(r.preferred_schedule)],
    ['Scheduled', fmt(r.scheduled_date)],
    ['Completed', fmt(r.completion_date)],
    ['Filed', fmt(r.submitted_at)],
    ['SLA deadline', fmt(r.sla_deadline)],
    ['SLA breached', yesNo(r.exceeded_sla)],
    ['Document attached', yesNo(r.document_path)],
  ]);
  heading(doc, 'Description');
  paragraph(doc, r.description || 'No description provided.');
  locationBlock(doc, r);
  reporterBlock(doc, r);
  notesBlock(doc, r);
  historyBlock(doc, r);
  footer(doc);
}

// One entry point so controllers stay uniform.
const WRITERS = { complaint: writeComplaintReport, wildlife: writeWildlifeReport, request: writeRequestReport };

function writeReport(doc, kind, record, meta = {}) {
  const write = WRITERS[kind];
  if (!write) throw new Error(`Unknown report kind: ${kind}`);
  write(doc, record, meta);
}

function documentFor(kind, ref) {
  return createReportDocument(`CENROWATCH ${KINDS[kind].label} ${ref}`);
}

module.exports = { writeReport, documentFor, writeComplaintReport, writeWildlifeReport, writeRequestReport };
